using GdUnit4;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using IdyllicMultiplayerProject.Testament.Utils;
using Judgement;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using static GdUnit4.Assertions;

namespace IdyllicMultiplayerProject.Testament;

[TestSuite]
public class JudgementTest
{
//     private const string DddRegistryText = """
//                                            User
//                                            Document
//                                            Customer
//                                            """;
//     
//     
//     [TestCase]
//     public void TestJudgement()
//     {
//         // Create an instance of the source generator.
//         var generator = new SourceGeneratorWithAdditionalFiles();
//
//         // Source generators should be tested using 'GeneratorDriver'.
//         GeneratorDriver driver = CSharpGeneratorDriver.Create(generator);
//
//         // Add the additional file separately from the compilation.
//         driver = driver.AddAdditionalTexts(
//             ImmutableArray.Create<AdditionalText>(
//                 new TestAdditionalFile("./DDD.UbiquitousLanguageRegistry.txt", DddRegistryText))
//         );
//
//         // To run generators, we can use an empty compilation.
//         var compilation = CSharpCompilation.Create(nameof(JudgementTest));
//
//         // Run generators. Don't forget to use the new compilation rather than the previous one.
//         driver.RunGeneratorsAndUpdateCompilation(compilation, out var newCompilation, out _);
//
//         // Retrieve all files in the compilation.
//         var generatedFiles = newCompilation.SyntaxTrees
//             .Select(t => Path.GetFileName(t.FilePath))
//             .ToArray();
//
//         // In this case, it is enough to check the file name.
//         AssertBool(new[]
//         {
//             "User.g.cs",
//             "Document.g.cs",
//             "Customer.g.cs"
//         }.SequenceEqual(generatedFiles)).IsTrue();
//     }
//     
//     private const string VectorClassText = """
//
//                                            namespace TestNamespace;
//
//                                            [Generators.Report]
//                                            public partial class Vector3
//                                            {
//                                                public float X { get; set; }
//                                                public float Y { get; set; }
//                                                public float Z { get; set; }
//                                            }
//                                            """;
//
//     private const string ExpectedGeneratedClassText = """
//                                                       // <auto-generated/>
//
//                                                       using System;
//                                                       using System.Collections.Generic;
//
//                                                       namespace TestNamespace;
//
//                                                       partial class Vector3
//                                                       {
//                                                           public IEnumerable<string> Report()
//                                                           {
//                                                               yield return $"X:{this.X}";
//                                                               yield return $"Y:{this.Y}";
//                                                               yield return $"Z:{this.Z}";
//                                                           }
//                                                       }
//
//                                                       """;
//
//     [TestCase]
//     public void GenerateReportMethod()
//     {
//         // Create an instance of the source generator.
//         var generator = new SourceGeneratorWithAttributes();
//
//         // Source generators should be tested using 'GeneratorDriver'.
//         var driver = CSharpGeneratorDriver.Create(generator);
//
//         // We need to create a compilation with the required source code.
//         var compilation = CSharpCompilation.Create(nameof(JudgementTest),
//             new[] { CSharpSyntaxTree.ParseText(VectorClassText) },
//             new[]
//             {
//                 // To support 'System.Attribute' inheritance, add reference to 'System.Private.CoreLib'.
//                 MetadataReference.CreateFromFile(typeof(object).Assembly.Location)
//             });
//
//         // Run generators and retrieve all results.
//         var runResult = driver.RunGenerators(compilation).GetRunResult();
//
//         // All generated files can be found in 'RunResults.GeneratedTrees'.
//         var generatedFileSyntax = runResult.GeneratedTrees.Single(t => t.FilePath.EndsWith("Vector3.g.cs"));
//
//         // Complex generators should be tested using text comparison.
//         AssertBool(Regex.Replace(ExpectedGeneratedClassText, @"\s", "")
//                    == Regex.Replace(generatedFileSyntax.GetText().ToString(), @"\s", ""))
//             .IsTrue();
//     }
//
//     [TestCase]
//     public void HelloWorldTest()
//     {
//         var generator = new SignalBusGenerator();
//         var driver = CSharpGeneratorDriver.Create(generator);
//         var compilation = CSharpCompilation.Create(nameof(JudgementTest));
//         // Run generators. Don't forget to use the new compilation rather than the previous one.
//         driver.RunGeneratorsAndUpdateCompilation(compilation, out var newCompilation, out _);
//
//         // Retrieve all files in the compilation.
//         var generatedFiles = newCompilation.SyntaxTrees
//             .Select(t => Path.GetFileName(t.FilePath))
//             .ToArray();
//     }
}