using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Judgement;

/// <summary>
/// I feel like a caveman writing SignalBus template code so let's hope I can automate this!
/// </summary>
[Generator]
public class SignalBusGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var userSignalDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: (syntaxNode, cancellationToken) => syntaxNode is ClassDeclarationSyntax,
                transform: (generatorSyntaxContext, cancellationToken) =>
                {
                    if (generatorSyntaxContext.Node is not ClassDeclarationSyntax classDeclarationSyntax)
                        return null; 
        
                    if (generatorSyntaxContext.SemanticModel.GetDeclaredSymbol(classDeclarationSyntax,
                            cancellationToken) is not ITypeSymbol typedSymbol)
                        return null;

                    if (typedSymbol.IsAbstract)
                        return null;
                    
                    if (typedSymbol.BaseType is null)
                        return null;

                    if (typedSymbol.BaseType.Name != "UserSignalArgs"
                        && typedSymbol.BaseType.Name != "CancellableSignalArgs"
                        && typedSymbol.BaseType.Name != "HandledSignalArgs")
                        return null;
                    
                    return typedSymbol;
                }).Where(typedSymbol => typedSymbol is not null);

        
        context.RegisterSourceOutput(userSignalDeclarations, HelloWorld);
    }

    private void HelloWorld(SourceProductionContext context, ITypeSymbol? typedSymbol)
    {
        if (typedSymbol is null)
            return;
        
        var symbolNameSpace = typedSymbol.ContainingNamespace.ToDisplayString();
        var className = typedSymbol.Name;
        var properties = typedSymbol.GetMembers().ToList();
        
        // begin creating the source we'll inject into the users compilation
        var sourceBuilder = new StringBuilder(@"using System;
using ENet;
using Godot;
using Google.Protobuf.Collections;
");
        sourceBuilder.AppendLine($"using {symbolNameSpace};");
        sourceBuilder.AppendLine(@"
namespace Game.Temperance.Signals;

#nullable enable
// <<auto-generated by the SignalBusGenerator.cs>>
public partial class SignalBus
{
");
        sourceBuilder.AppendLine($"    // Namespace: {symbolNameSpace}");
        sourceBuilder.AppendLine($"    // Classname: {className}");
        
        foreach (var typedInterface in typedSymbol.AllInterfaces)
        {
            sourceBuilder.AppendLine($"    // Interface: {typedInterface}");
        }
        
        if (typedSymbol.BaseType is not null)
            sourceBuilder.AppendLine($"    // BaseType: {typedSymbol.BaseType.Name}");

        var constructor = properties.Find(x => x.Name == ".ctor");
        var constructionParametersWithTypes = "";
        var constructionParameterNames = "";
        if (constructor is IMethodSymbol constructorSymbol)
        {
            foreach (var parameter in constructorSymbol.Parameters)
            {
                sourceBuilder.AppendLine($"    // Construction Parameter: {parameter.Type.Name} {parameter.Name}");
                constructionParametersWithTypes += parameter.Type.Name;
                if (parameter.Type is INamedTypeSymbol namedType && namedType.IsGenericType)
                {
                    constructionParametersWithTypes += "<";
                    foreach (var argument in namedType.TypeArguments)
                    {
                        constructionParametersWithTypes += argument.Name + ", ";
                    }
                    constructionParametersWithTypes = constructionParametersWithTypes.Substring(0, constructionParametersWithTypes.Length - 2);
                    constructionParametersWithTypes += ">";
                }
                constructionParametersWithTypes += " " + parameter.Name + ", ";
                constructionParameterNames += parameter.Name + ", ";
            }
        }
        
        foreach (var property in properties)
        {
            sourceBuilder.AppendLine($"    // Property: {property.Name}");
        }

        // finish creating the source to inject
        sourceBuilder.AppendLine($@"
    public delegate void {className}Handler({constructionParametersWithTypes}ref {className} args);
    public event {className}Handler? {className};
    public void Emit{className}({constructionParametersWithTypes}ref {className} args)");
        sourceBuilder.AppendLine(@"    {");
        sourceBuilder.AppendLine($"         {className}?.Invoke({constructionParameterNames}ref args);");
        sourceBuilder.AppendLine(@"    }
}");

        // inject the created source into the users compilation
        context.AddSource($"SignalBus.{className}.g.cs", SourceText.From(sourceBuilder.ToString(), Encoding.UTF8));
    }
}