syntax = "proto3";
option csharp_namespace = "Games.Resources.ProtocolBuffers";

import "godot_types.proto";

message NodeStates {
  repeated NodeState node_state = 1;
}

message NodeState {
  uint32 sequence = 1;
  string node_network_guid = 2;
  GdVector3 global_position = 3;
  GdVector3 global_rotation = 4;
  GdVector3 global_scale = 5;
  MovementComponentState movement_component_state = 6;
}

message MovementComponentState {
  GdVector2 input_direction = 1;
  optional float movement_speed = 2;
}