name: gdUnit4-ci-tests
run-name: ${{ github.head_ref || github.ref_name }}-ci

on:
  pull_request:
    paths-ignore:
      - '**.yml'
      - '**.md'
  workflow_dispatch:


concurrency:
  group: gdUnit4-ci-${{ github.event.number }}
  cancel-in-progress: true


jobs:
  unit-test:
    name: "gdUnit4 CI Unit Test"
    runs-on: 'ubuntu-24.04'
    timeout-minutes: 10 # The overall timeout
    permissions:
      actions: write
      checks: write
      contents: write
      pull-requests: write
      statuses: write
    steps:
      # checkout your repository
      - uses: actions/checkout@v4
        with:
          lfs: true
      # run tests by using the gdUnit4-action with Godot version 4.2.1 and the latest GdUnit4 release 
      - uses: godot-gdunit-labs/gdUnit4-action@v1
        with:
          godot-version: '4.7.0'       # Required: Godot version to use
          godot-net: true
          dotnet-version: net10.0
          paths: 'res://Testament'         # Required: Test directory
          timeout: 10                  # Optional: Test timeout in minutes
          version: 'latest'            # Optional: GdUnit4 version
